import { Epilogue } from "next/font/google";
import "@workspace/ui/globals.css";
import type { Metadata } from "next";
import { TanstackReactQueryProvider } from "./TanstackReactQueryProvider";
import { Toaster } from "react-hot-toast";

const fontEpilogue = Epilogue({
  subsets: ["latin"],
  variable: "--font-epilogue",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${fontEpilogue.variable} font-sans antialiased `}>
        <TanstackReactQueryProvider>{children}</TanstackReactQueryProvider>
        <Toaster />
      </body>
    </html>
  );
}
