import type { Metadata } from "next";
import { Epilogue } from "next/font/google";
import "@workspace/ui/styles/globals.css";
import { TanstackReactQueryProvider } from "./TanstackReactQueryProvider";
import ToasterClient from "../components/ToasterClient";
import { AuthProvider } from "../contexts/AuthContext";
import { WorkspaceProvider } from "../contexts/WorkspaceContext";
import { ThemeProvider } from "../contexts/ThemeContext";

const fontEpilogue = Epilogue({
  subsets: ["latin"],
  variable: "--font-epilogue",
});

export const metadata: Metadata = {
  title: "AI Knowledge Hub",
  description: "Generated by create next app",
};

// Applies the saved (or system) theme before first paint to avoid a flash.
const themeInitScript = `
(function () {
  try {
    var stored = localStorage.getItem('theme');
    var isDark = stored
      ? stored === 'dark'
      : window.matchMedia('(prefers-color-scheme: dark)').matches;
    if (isDark) document.documentElement.classList.add('dark');
  } catch (e) {}
})();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <body className={`${fontEpilogue.variable} font-sans antialiased `}>
        <TanstackReactQueryProvider>
          <ThemeProvider>
            <AuthProvider>
              <WorkspaceProvider>{children}</WorkspaceProvider>
            </AuthProvider>
          </ThemeProvider>
        </TanstackReactQueryProvider>
        <ToasterClient />
      </body>
    </html>
  );
}
